#!/bin/bash
#
# Retries a command.
#
# The retry count is given by ATTEMPTS (default 5), the initial
# backoff timeout is given by TIMEOUT in seconds (default 1.)
#
# Successive backoffs double the timeout.
#
# Beware of set -e killing your whole script!

function retry_execution {
  local max_attempts=${ATTEMPTS-5}
  local timeout=${TIMEOUT-1}
  local attempt=0
  local exitCode=0

  while [[ $attempt < $max_attempts ]]
  do
    "$@"
    exitCode=$?

    if [[ $exitCode == 0 ]]
    then
      break
    fi

    echo "Failure! Retrying in $timeout.." 1>&2
    sleep $timeout
    attempt=$(( attempt + 1 ))
    timeout=$(( timeout * 2 ))
  done

  if [[ $exitCode != 0 ]]
  then
    echo "You've failed me for the last time! ($@)" 1>&2
  fi

  return $exitCode
}

retry_execution $@
