#!/bin/bash
#
# Retries a command.
#
# The retry count is given by ATTEMPTS (default 5), the initial
# backoff timeout is given by TIMEOUT in seconds (default 1.)
#
# Successive backoffs double the timeout.
#
# Beware of set -e killing your whole script!

function retry_execution {
  local __n__=3;       # retry 3 times by default
  local __naptime__=0; # don't sleep by default

  # parsing command line options

  while true; do
    case "$1" in

      -t|--times)
        shift   # drop --times from the args
        __n__="$1"  # $1 contains the number of iterations
        shift
        ;;

      -n|--naptime)
        shift   # drop --naptime from the args
        __n__="$1"  # $1 contains the naptime
        shift
        ;;

      *)
        break;  # no more args to parse

    esac
  done


  # executing command

  local __cmd__="$@";
  local __result__="0";

  for __i__ in $(seq 1 $__n__); do
    eval "$__cmd__";

    __result__="$?";
    # echo "$__result__";

    if [ $__result__ -eq "0" ]; then
      exit 0; # command executed succesfully
    else
      if [[ $__i__ == $__n__ ]]; then
        echo "[$__i__/$__n__] Execution Failed with exit status $__result__. No more retries."

        exit $__result__; # exit with the same exit status as the invoked command
      else
        echo "[$__i__/$__n__] Execution Failed with exit status $__result__. Retrying."
      fi
    fi
  done
}

retry_execution $@
